### PR TITLE
Restructure repository root assets

### LINKED ISSUE #20: general factoring
- more class orientation
- better name for `linkml_round_trips` folder, broken out into topical subdirectories

### PR DESCRIPTION
**Pull request by sujaypatil96**
Restructured various assets in the root of the repo. Some of the major changes are as mentioned:

* Move the `freezes` folder into `assets/freezes`
* Move all web assets into a `www` folder in the root of the repo. Another possible name for the folder can be `web`
* Modify paths to www assets within `main.html` and `main.css`
* Modify the Makefile so it accommodates the `www` paths
* Remove old `linkml_round_trips` folder and associated files

This PR should be reviewed and merged only after PR #29 is fully completed.

### CODE REVIEW

**Comment by turbomam** [comment]
> * Move the `freezes` folder into `assets/freezes`

Great, that's much better

**Comment by turbomam** [comment]
> * Move all web assets into a `www` folder in the root of the repo

Does that mean moving them out of the `docs` folder? I'm not in favor of that right now. `docs` is being used to host the GH pages.

**Comment by turbomam** [comment]
See also our BBOP slack channel

**Comment by sujaypatil96** [comment]
Closing this PR in favor of another PR which will be opened after PR #29 is merged.

**Pull request closed without merging**
